package exh.source

// Lewd source IDs
const val LEWD_SOURCE_SERIES = 6900L
const val DEBUG_SOURCE_ID = 1L
const val EH_SOURCE_ID = LEWD_SOURCE_SERIES + 1
const val EXH_SOURCE_ID = LEWD_SOURCE_SERIES + 2
const val LANRARAGI_ONE_SOURCE_ID = LEWD_SOURCE_SERIES + 3
const val LANRARAGI_TWO_SOURCE_ID = LEWD_SOURCE_SERIES + 4
const val LANRARAGI_THREE_SOURCE_ID = LEWD_SOURCE_SERIES + 5
const val GRRL_POWER_COMIC_SOURCE_ID = LEWD_SOURCE_SERIES + 6
const val QUESTIONABLE_CONTENT_SOURCE_ID = LEWD_SOURCE_SERIES + 7
const val MANGADEX_SOURCE_ID = LEWD_SOURCE_SERIES + 8
const val MERGED_SOURCE_ID = LEWD_SOURCE_SERIES + 69
